# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  
  config.vm.base_mac = "080027880CA6"

  config.ssh.shell = "/bin/sh"
  config.vm.synced_folder "..", "/home/bigcgi/bigcgi-repo", type: "rsync", disabled: false, rsync__exclude: ".git/", owner: "bigcgi", group: "bigcgi"
  config.vm.synced_folder ".", "/vagrant", type: "rsync", disabled: true, owner: "bigcgi", group: "bigcgi"

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "freebsd/FreeBSD-10.3-RELEASE"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
  config.vm.provision "shell", path: "provision.sh"
  
end
